#!/usr/bin/python3
from sys import argv

def factorize(check_num):

    i = 2

    if check_num < 2:
        return
    
    while check_num % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(check_num, check_num / i, i))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as f:
        line = f.readline()

        while line != "":
            checK_num = int(line.split('\n')[0])
            factorize(check_num)
            line = f.readline()
except:
    pass
